# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_train.ui'
#
# Created: Fri Sep 22 10:37:23 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_page_arch_train(object):
    def setupUi(self, page_arch_train):
        page_arch_train.setObjectName(_fromUtf8("page_arch_train"))
        page_arch_train.resize(989, 674)
        self.centralwidget = QtGui.QWidget(page_arch_train)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 991, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(500, 80, 481, 191))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 461, 161))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8("imagens/network_layout.PNG")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 331, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 80, 481, 551))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.pb_train = QtGui.QPushButton(self.groupBox_3)
        self.pb_train.setGeometry(QtCore.QRect(180, 400, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pb_train.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/raio_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_train.setIcon(icon)
        self.pb_train.setIconSize(QtCore.QSize(25, 25))
        self.pb_train.setObjectName(_fromUtf8("pb_train"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 441, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.bar_green = QtGui.QLabel(self.groupBox_3)
        self.bar_green.setGeometry(QtCore.QRect(290, 230, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bar_green.setFont(font)
        self.bar_green.setText(_fromUtf8(""))
        self.bar_green.setPixmap(QtGui.QPixmap(_fromUtf8("imagens/Bar-green.png")))
        self.bar_green.setScaledContents(True)
        self.bar_green.setObjectName(_fromUtf8("bar_green"))
        self.bar_blue = QtGui.QLabel(self.groupBox_3)
        self.bar_blue.setGeometry(QtCore.QRect(310, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bar_blue.setFont(font)
        self.bar_blue.setText(_fromUtf8(""))
        self.bar_blue.setPixmap(QtGui.QPixmap(_fromUtf8("imagens/Bar_blue.png")))
        self.bar_blue.setScaledContents(True)
        self.bar_blue.setObjectName(_fromUtf8("bar_blue"))
        self.bar_red = QtGui.QLabel(self.groupBox_3)
        self.bar_red.setGeometry(QtCore.QRect(300, 190, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bar_red.setFont(font)
        self.bar_red.setText(_fromUtf8(""))
        self.bar_red.setPixmap(QtGui.QPixmap(_fromUtf8("imagens/Bar-Red.png")))
        self.bar_red.setScaledContents(True)
        self.bar_red.setObjectName(_fromUtf8("bar_red"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(340, 240, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(340, 160, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(340, 200, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(20, 200, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.sb_nr_epochs = QtGui.QSpinBox(self.groupBox_3)
        self.sb_nr_epochs.setGeometry(QtCore.QRect(150, 200, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sb_nr_epochs.setFont(font)
        self.sb_nr_epochs.setMinimum(100)
        self.sb_nr_epochs.setMaximum(1000)
        self.sb_nr_epochs.setObjectName(_fromUtf8("sb_nr_epochs"))
        self.pb_teste = QtGui.QPushButton(self.groupBox_3)
        self.pb_teste.setEnabled(False)
        self.pb_teste.setGeometry(QtCore.QRect(390, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pb_teste.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_teste.setIcon(icon1)
        self.pb_teste.setObjectName(_fromUtf8("pb_teste"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(20, 240, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.sb_rate = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.sb_rate.setGeometry(QtCore.QRect(150, 240, 62, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sb_rate.setFont(font)
        self.sb_rate.setMinimum(0.01)
        self.sb_rate.setMaximum(1.0)
        self.sb_rate.setSingleStep(0.01)
        self.sb_rate.setObjectName(_fromUtf8("sb_rate"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(20, 280, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.sb_momentum = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.sb_momentum.setGeometry(QtCore.QRect(150, 280, 62, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sb_momentum.setFont(font)
        self.sb_momentum.setMinimum(0.01)
        self.sb_momentum.setMaximum(1.0)
        self.sb_momentum.setSingleStep(0.01)
        self.sb_momentum.setProperty("value", 0.99)
        self.sb_momentum.setObjectName(_fromUtf8("sb_momentum"))
        self.count_1 = QtGui.QLabel(self.groupBox_3)
        self.count_1.setGeometry(QtCore.QRect(410, 160, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.count_1.setFont(font)
        self.count_1.setObjectName(_fromUtf8("count_1"))
        self.count_2 = QtGui.QLabel(self.groupBox_3)
        self.count_2.setGeometry(QtCore.QRect(410, 200, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.count_2.setFont(font)
        self.count_2.setObjectName(_fromUtf8("count_2"))
        self.count_3 = QtGui.QLabel(self.groupBox_3)
        self.count_3.setGeometry(QtCore.QRect(410, 240, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.count_3.setFont(font)
        self.count_3.setObjectName(_fromUtf8("count_3"))
        self.pb_default = QtGui.QPushButton(self.groupBox_3)
        self.pb_default.setGeometry(QtCore.QRect(80, 320, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pb_default.setFont(font)
        self.pb_default.setObjectName(_fromUtf8("pb_default"))
        self.sb_nr_neurons = QtGui.QSpinBox(self.groupBox_3)
        self.sb_nr_neurons.setGeometry(QtCore.QRect(150, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sb_nr_neurons.setFont(font)
        self.sb_nr_neurons.setMinimum(1)
        self.sb_nr_neurons.setMaximum(20)
        self.sb_nr_neurons.setProperty("value", 4)
        self.sb_nr_neurons.setObjectName(_fromUtf8("sb_nr_neurons"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pb_cancel = QtGui.QPushButton(self.centralwidget)
        self.pb_cancel.setGeometry(QtCore.QRect(880, 600, 101, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/1351621507_Delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_cancel.setIcon(icon2)
        self.pb_cancel.setIconSize(QtCore.QSize(20, 20))
        self.pb_cancel.setObjectName(_fromUtf8("pb_cancel"))
        self.pb_back = QtGui.QPushButton(self.centralwidget)
        self.pb_back.setEnabled(True)
        self.pb_back.setGeometry(QtCore.QRect(614, 600, 101, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/1351621543_Previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_back.setIcon(icon3)
        self.pb_back.setIconSize(QtCore.QSize(20, 20))
        self.pb_back.setObjectName(_fromUtf8("pb_back"))
        self.pb_next = QtGui.QPushButton(self.centralwidget)
        self.pb_next.setEnabled(True)
        self.pb_next.setGeometry(QtCore.QRect(720, 600, 101, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/1351621545_Next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_next.setIcon(icon4)
        self.pb_next.setIconSize(QtCore.QSize(20, 20))
        self.pb_next.setObjectName(_fromUtf8("pb_next"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(500, 290, 481, 291))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.pb_plot = QtGui.QPushButton(self.groupBox_4)
        self.pb_plot.setGeometry(QtCore.QRect(180, 230, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pb_plot.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/Plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_plot.setIcon(icon5)
        self.pb_plot.setIconSize(QtCore.QSize(20, 20))
        self.pb_plot.setObjectName(_fromUtf8("pb_plot"))
        self.sb_nr_neighbors = QtGui.QSpinBox(self.groupBox_4)
        self.sb_nr_neighbors.setGeometry(QtCore.QRect(150, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sb_nr_neighbors.setFont(font)
        self.sb_nr_neighbors.setMinimum(1)
        self.sb_nr_neighbors.setMaximum(10)
        self.sb_nr_neighbors.setProperty("value", 2)
        self.sb_nr_neighbors.setObjectName(_fromUtf8("sb_nr_neighbors"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.pb_predict = QtGui.QPushButton(self.groupBox_4)
        self.pb_predict.setGeometry(QtCore.QRect(170, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pb_predict.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/Magic-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_predict.setIcon(icon6)
        self.pb_predict.setIconSize(QtCore.QSize(25, 25))
        self.pb_predict.setObjectName(_fromUtf8("pb_predict"))
        page_arch_train.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(page_arch_train)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        page_arch_train.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(page_arch_train)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        page_arch_train.setStatusBar(self.statusbar)

        self.retranslateUi(page_arch_train)
        QtCore.QMetaObject.connectSlotsByName(page_arch_train)

    def retranslateUi(self, page_arch_train):
        page_arch_train.setWindowTitle(_translate("page_arch_train", "Architeture and Training Network", None))
        self.label.setText(_translate("page_arch_train", "Architeture and Training Network", None))
        self.groupBox_2.setTitle(_translate("page_arch_train", "Neural Network", None))
        self.label_2.setText(_translate("page_arch_train", "Set the number of neurons in the fitting network\'s hidden layer.", None))
        self.groupBox_3.setTitle(_translate("page_arch_train", "Train Network", None))
        self.pb_train.setText(_translate("page_arch_train", " Train", None))
        self.label_6.setText(_translate("page_arch_train", "Training multiple times will generate different results due to different initial\n"
"conditions and sampling.", None))
        self.label_7.setText(_translate("page_arch_train", "Testing:", None))
        self.label_8.setText(_translate("page_arch_train", "Training:", None))
        self.label_9.setText(_translate("page_arch_train", "Validation:", None))
        self.label_10.setText(_translate("page_arch_train", "Configurations:", None))
        self.label_11.setText(_translate("page_arch_train", "Number of Epochs:", None))
        self.pb_teste.setText(_translate("page_arch_train", " Test", None))
        self.label_12.setText(_translate("page_arch_train", "Leaning rate:", None))
        self.label_13.setText(_translate("page_arch_train", "Momentum:", None))
        self.count_1.setText(_translate("page_arch_train", "0", None))
        self.count_2.setText(_translate("page_arch_train", "0", None))
        self.count_3.setText(_translate("page_arch_train", "0", None))
        self.pb_default.setText(_translate("page_arch_train", "Default", None))
        self.label_4.setText(_translate("page_arch_train", "Number of Hidden\n"
"Neurons:", None))
        self.pb_cancel.setText(_translate("page_arch_train", " Cancel", None))
        self.pb_back.setText(_translate("page_arch_train", "  Back", None))
        self.pb_next.setText(_translate("page_arch_train", "  Next", None))
        self.groupBox_4.setTitle(_translate("page_arch_train", "kNN Regression", None))
        self.pb_plot.setText(_translate("page_arch_train", "Plot", None))
        self.label_14.setText(_translate("page_arch_train", "k-NNeighbors:", None))
        self.label_15.setText(_translate("page_arch_train", " k-nearest neighbors (k-NN) is a method used for classification and regression.\n"
" In k-NN regression, the output is the property value for the object.\n"
"This value is the average of the values of its k nearest neighbors.", None))
        self.pb_predict.setText(_translate("page_arch_train", "Predict", None))

